-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dma_demo_v_tpg_0_2_tpgPatternCrossHatch is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    y : IN STD_LOGIC_VECTOR (15 downto 0);
    x : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    color : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of dma_demo_v_tpg_0_2_tpgPatternCrossHatch is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv14_F : STD_LOGIC_VECTOR (13 downto 0) := "00000000001111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal yCount_V_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal vHatch : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal xCount_V_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal whiYuv_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal whiYuv_1_ce0 : STD_LOGIC;
    signal whiYuv_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal blkYuv_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal blkYuv_1_ce0 : STD_LOGIC;
    signal blkYuv_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_reg_122 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_218_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln1437_fu_232_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln1443_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1443_reg_541 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1443_reg_541_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1443_fu_246_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1443_reg_545 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1443_reg_545_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1443_1_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1443_1_reg_551 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1443_1_reg_551_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1443_1_reg_551_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1443_2_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1443_2_reg_557 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp57_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp59_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1467_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1467_reg_576 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1467_reg_576_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1467_reg_576_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1443_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1443_reg_580 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_fu_330_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln878_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_592 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln870_1_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln870_1_reg_596 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv_i10_fu_491_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv_i_fu_498_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal grp_reg_ap_uint_10_s_fu_301_d : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reg_ap_uint_10_s_fu_301_ap_return : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reg_ap_uint_10_s_fu_301_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call10 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call10 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call10 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call10 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call10 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp33 : BOOLEAN;
    signal ap_phi_reg_pp0_iter2_empty_reg_122 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1448_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_reg_122 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_reg_122 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_storemerge_phi_fu_143_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln692_fu_417_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter2_storemerge_reg_140 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln691_2_fu_430_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter0_agg_result_0_reg_149 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_agg_result_0_reg_149 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_agg_result_0_reg_149 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter3_agg_result_0_reg_149 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter4_agg_result_0_reg_149 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_1_reg_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_1_reg_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_1_reg_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_val_V_1_reg_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter4_pix_val_V_1_reg_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_2_reg_185 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_2_reg_185 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_2_reg_185 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_val_V_2_reg_185 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter4_pix_val_V_2_reg_185 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1503_fu_462_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1494_fu_486_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln691_fu_371_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln1435_fu_208_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln1435_fu_212_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln1437_fu_228_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln1443_fu_236_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1443_fu_260_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln1435_fu_204_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln1443_1_fu_250_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub29_fu_272_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1437_fu_307_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_316_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1347_fu_326_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln870_fu_352_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln870_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1503_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1503_1_fu_443_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln1503_fu_454_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln1494_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1494_1_fu_467_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln1494_fu_478_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln1494_2_fu_505_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_270 : BOOLEAN;
    signal ap_condition_265 : BOOLEAN;
    signal ap_condition_305 : BOOLEAN;
    signal ap_condition_224 : BOOLEAN;
    signal ap_condition_314 : BOOLEAN;
    signal ap_condition_209 : BOOLEAN;
    signal ap_condition_297 : BOOLEAN;
    signal ap_condition_258 : BOOLEAN;
    signal ap_condition_277 : BOOLEAN;
    signal ap_condition_280 : BOOLEAN;
    signal ap_condition_249 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component dma_demo_v_tpg_0_2_reg_ap_uint_10_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        d : IN STD_LOGIC_VECTOR (9 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component dma_demo_v_tpg_0_2_tpgPatternCrossHatch_whiYuv_1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component dma_demo_v_tpg_0_2_tpgPatternCrossHatch_blkYuv_1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    whiYuv_1_U : component dma_demo_v_tpg_0_2_tpgPatternCrossHatch_whiYuv_1
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => whiYuv_1_address0,
        ce0 => whiYuv_1_ce0,
        q0 => whiYuv_1_q0);

    blkYuv_1_U : component dma_demo_v_tpg_0_2_tpgPatternCrossHatch_blkYuv_1
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => blkYuv_1_address0,
        ce0 => blkYuv_1_ce0,
        q0 => blkYuv_1_q0);

    grp_reg_ap_uint_10_s_fu_301 : component dma_demo_v_tpg_0_2_reg_ap_uint_10_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        d => grp_reg_ap_uint_10_s_fu_301_d,
        ap_return => grp_reg_ap_uint_10_s_fu_301_ap_return,
        ap_ce => grp_reg_ap_uint_10_s_fu_301_ap_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_empty_reg_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_265)) then
                if ((ap_const_boolean_1 = ap_condition_270)) then 
                    ap_phi_reg_pp0_iter2_empty_reg_122 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_empty_reg_122 <= ap_phi_reg_pp0_iter1_empty_reg_122;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_agg_result_0_reg_149_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((empty_reg_122 = ap_const_lv1_0) and (icmp_ln878_reg_592 = ap_const_lv1_1) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_1) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)) or ((empty_reg_122 = ap_const_lv1_0) and (icmp_ln870_1_reg_596 = ap_const_lv1_0) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_1) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)))) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((empty_reg_122 = ap_const_lv1_0) and (icmp_ln878_reg_592 = ap_const_lv1_1) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)) or ((empty_reg_122 = ap_const_lv1_0) and (icmp_ln870_1_reg_596 = ap_const_lv1_0) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)))))) then 
                ap_phi_reg_pp0_iter4_agg_result_0_reg_149 <= ap_const_lv1_0;
            elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((((icmp_ln870_1_reg_596 = ap_const_lv1_1) and (icmp_ln878_reg_592 = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_1)) or ((empty_reg_122 = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_1))) or ((icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_1))) or ((cmp57_fu_278_p2 = ap_const_lv1_1) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_1)))) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((((icmp_ln870_1_reg_596 = ap_const_lv1_1) and (icmp_ln878_reg_592 = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_0)) or ((empty_reg_122 = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_0))) or ((icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_0))) or ((cmp57_fu_278_p2 = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_1)))))) then 
                ap_phi_reg_pp0_iter4_agg_result_0_reg_149 <= ap_const_lv1_1;
            elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                ap_phi_reg_pp0_iter4_agg_result_0_reg_149 <= ap_phi_reg_pp0_iter3_agg_result_0_reg_149;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_pix_val_V_1_reg_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_297)) then
                if ((ap_const_boolean_1 = ap_condition_209)) then 
                    ap_phi_reg_pp0_iter4_pix_val_V_1_reg_168 <= blkYuv_1_q0;
                elsif ((ap_const_boolean_1 = ap_condition_314)) then 
                    ap_phi_reg_pp0_iter4_pix_val_V_1_reg_168 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_condition_224)) then 
                    ap_phi_reg_pp0_iter4_pix_val_V_1_reg_168 <= whiYuv_1_q0;
                elsif ((ap_const_boolean_1 = ap_condition_305)) then 
                    ap_phi_reg_pp0_iter4_pix_val_V_1_reg_168 <= ap_const_lv8_FF;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_pix_val_V_1_reg_168 <= ap_phi_reg_pp0_iter3_pix_val_V_1_reg_168;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_pix_val_V_2_reg_185_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((empty_reg_122 = ap_const_lv1_0) and (icmp_ln878_reg_592 = ap_const_lv1_1) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_1) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)) or ((empty_reg_122 = ap_const_lv1_0) and (icmp_ln870_1_reg_596 = ap_const_lv1_0) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_1) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)))) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((empty_reg_122 = ap_const_lv1_0) and (icmp_ln878_reg_592 = ap_const_lv1_1) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)) or ((empty_reg_122 = ap_const_lv1_0) and (icmp_ln870_1_reg_596 = ap_const_lv1_0) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)))))) then 
                ap_phi_reg_pp0_iter4_pix_val_V_2_reg_185 <= conv_i_fu_498_p3;
            elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((((icmp_ln870_1_reg_596 = ap_const_lv1_1) and (icmp_ln878_reg_592 = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_1)) or ((empty_reg_122 = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_1))) or ((icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_1))) or ((cmp57_fu_278_p2 = ap_const_lv1_1) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_1)))) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((((icmp_ln870_1_reg_596 = ap_const_lv1_1) and (icmp_ln878_reg_592 = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_0)) or ((empty_reg_122 = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_0))) or ((icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_0))) or ((cmp57_fu_278_p2 = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_1)))))) then 
                ap_phi_reg_pp0_iter4_pix_val_V_2_reg_185 <= conv_i10_fu_491_p3;
            elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
                ap_phi_reg_pp0_iter4_pix_val_V_2_reg_185 <= ap_phi_reg_pp0_iter3_pix_val_V_2_reg_185;
            end if; 
        end if;
    end process;

    empty_reg_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_249)) then
                if ((ap_const_boolean_1 = ap_condition_280)) then 
                    empty_reg_122 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_277)) then 
                    empty_reg_122 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_condition_258)) then 
                    empty_reg_122 <= vHatch;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_reg_122 <= ap_phi_reg_pp0_iter2_empty_reg_122;
                end if;
            end if; 
        end if;
    end process;

    vHatch_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((ap_const_lv1_1 = and_ln1443_fu_312_p2) and (icmp_ln1443_reg_541 = ap_const_lv1_0)) or ((icmp_ln1443_1_reg_551 = ap_const_lv1_1) and (icmp_ln1443_reg_541 = ap_const_lv1_1)))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((ap_const_lv1_1 = and_ln1448_fu_361_p2) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1443_reg_541_pp0_iter1_reg = ap_const_lv1_1)) or ((ap_const_lv1_0 = and_ln1443_reg_580) and (ap_const_lv1_1 = and_ln1448_fu_361_p2) and (icmp_ln1443_reg_541_pp0_iter1_reg = ap_const_lv1_0)))))) then 
                vHatch <= ap_const_lv1_1;
            elsif (((ap_const_lv1_0 = and_ln1448_fu_361_p2) and (ap_const_lv1_0 = and_ln1443_reg_580) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln1443_reg_541_pp0_iter1_reg = ap_const_lv1_0))) then 
                vHatch <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    xCount_V_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((icmp_ln878_fu_405_p2 = ap_const_lv1_1) and (icmp_ln1467_reg_576_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0)) or ((icmp_ln870_1_fu_411_p2 = ap_const_lv1_0) and (icmp_ln1467_reg_576_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0))))) then 
                xCount_V_2 <= ap_phi_mux_storemerge_phi_fu_143_p4;
            elsif ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1467_reg_576 = ap_const_lv1_1) and (icmp_ln1443_1_reg_551 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1443_1_reg_551 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (icmp_ln870_1_fu_411_p2 = ap_const_lv1_1) and (icmp_ln878_fu_405_p2 = ap_const_lv1_0) and (icmp_ln1467_reg_576_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0)))) then 
                xCount_V_2 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    yCount_V_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((ap_const_lv1_1 = and_ln1443_fu_312_p2) and (icmp_ln1443_reg_541 = ap_const_lv1_0)) or ((icmp_ln1443_1_reg_551 = ap_const_lv1_1) and (icmp_ln1443_reg_541 = ap_const_lv1_1)))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (((ap_const_lv1_1 = and_ln1448_fu_361_p2) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1443_reg_541_pp0_iter1_reg = ap_const_lv1_1)) or ((ap_const_lv1_0 = and_ln1443_reg_580) and (ap_const_lv1_1 = and_ln1448_fu_361_p2) and (icmp_ln1443_reg_541_pp0_iter1_reg = ap_const_lv1_0)))))) then 
                yCount_V_2 <= ap_const_lv10_0;
            elsif (((ap_const_lv1_0 = and_ln1448_fu_361_p2) and (ap_const_lv1_0 = and_ln1443_reg_580) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln1443_reg_541_pp0_iter1_reg = ap_const_lv1_0))) then 
                yCount_V_2 <= add_ln691_fu_371_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1443_reg_541 = ap_const_lv1_0))) then
                and_ln1443_reg_580 <= and_ln1443_fu_312_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter1_agg_result_0_reg_149 <= ap_phi_reg_pp0_iter0_agg_result_0_reg_149;
                ap_phi_reg_pp0_iter1_empty_reg_122 <= ap_phi_reg_pp0_iter0_empty_reg_122;
                ap_phi_reg_pp0_iter1_pix_val_V_1_reg_168 <= ap_phi_reg_pp0_iter0_pix_val_V_1_reg_168;
                ap_phi_reg_pp0_iter1_pix_val_V_2_reg_185 <= ap_phi_reg_pp0_iter0_pix_val_V_2_reg_185;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_agg_result_0_reg_149 <= ap_phi_reg_pp0_iter1_agg_result_0_reg_149;
                ap_phi_reg_pp0_iter2_pix_val_V_1_reg_168 <= ap_phi_reg_pp0_iter1_pix_val_V_1_reg_168;
                ap_phi_reg_pp0_iter2_pix_val_V_2_reg_185 <= ap_phi_reg_pp0_iter1_pix_val_V_2_reg_185;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then
                ap_phi_reg_pp0_iter3_agg_result_0_reg_149 <= ap_phi_reg_pp0_iter2_agg_result_0_reg_149;
                ap_phi_reg_pp0_iter3_pix_val_V_1_reg_168 <= ap_phi_reg_pp0_iter2_pix_val_V_1_reg_168;
                ap_phi_reg_pp0_iter3_pix_val_V_2_reg_185 <= ap_phi_reg_pp0_iter2_pix_val_V_2_reg_185;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1443_1_reg_551 <= icmp_ln1443_1_fu_254_p2;
                icmp_ln1443_1_reg_551_pp0_iter1_reg <= icmp_ln1443_1_reg_551;
                icmp_ln1443_reg_541 <= icmp_ln1443_fu_240_p2;
                icmp_ln1443_reg_541_pp0_iter1_reg <= icmp_ln1443_reg_541;
                icmp_ln1467_reg_576_pp0_iter1_reg <= icmp_ln1467_reg_576;
                trunc_ln1443_reg_545 <= trunc_ln1443_fu_246_p1;
                trunc_ln1443_reg_545_pp0_iter1_reg <= trunc_ln1443_reg_545;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then
                icmp_ln1443_1_reg_551_pp0_iter2_reg <= icmp_ln1443_1_reg_551_pp0_iter1_reg;
                icmp_ln1467_reg_576_pp0_iter2_reg <= icmp_ln1467_reg_576_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1443_fu_240_p2 = ap_const_lv1_0))) then
                icmp_ln1443_2_reg_557 <= icmp_ln1443_2_fu_266_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1443_1_fu_254_p2 = ap_const_lv1_0))) then
                icmp_ln1467_reg_576 <= icmp_ln1467_fu_290_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (icmp_ln878_fu_405_p2 = ap_const_lv1_0) and (icmp_ln1467_reg_576_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0))) then
                icmp_ln870_1_reg_596 <= icmp_ln870_1_fu_411_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (icmp_ln1467_reg_576_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0))) then
                icmp_ln878_reg_592 <= icmp_ln878_fu_405_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1435_fu_212_p2 <= std_logic_vector(unsigned(trunc_ln1435_fu_208_p1) + unsigned(ap_const_lv14_F));
    add_ln1437_fu_307_p2 <= std_logic_vector(unsigned(trunc_ln1437_fu_232_p1) + unsigned(ap_const_lv14_F));
    add_ln1443_fu_260_p2 <= std_logic_vector(unsigned(zext_ln1437_fu_228_p1) + unsigned(ap_const_lv17_1FFFF));
    add_ln691_2_fu_430_p2 <= std_logic_vector(unsigned(xCount_V_2) + unsigned(ap_const_lv10_1));
    add_ln691_fu_371_p2 <= std_logic_vector(unsigned(yCount_V_2) + unsigned(ap_const_lv10_1));
    and_ln1443_fu_312_p2 <= (icmp_ln1443_2_reg_557 and icmp_ln1443_1_reg_551);
    and_ln1448_fu_361_p2 <= (icmp_ln870_fu_356_p2 and icmp_ln1443_1_reg_551_pp0_iter1_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp33 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call10 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_209_assign_proc : process(empty_reg_122, icmp_ln1443_1_reg_551_pp0_iter2_reg, cmp57_fu_278_p2, icmp_ln1467_reg_576_pp0_iter2_reg, icmp_ln878_reg_592, icmp_ln870_1_reg_596)
    begin
                ap_condition_209 <= (((empty_reg_122 = ap_const_lv1_0) and (icmp_ln878_reg_592 = ap_const_lv1_1) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)) or ((empty_reg_122 = ap_const_lv1_0) and (icmp_ln870_1_reg_596 = ap_const_lv1_0) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)));
    end process;


    ap_condition_224_assign_proc : process(empty_reg_122, icmp_ln1443_1_reg_551_pp0_iter2_reg, cmp57_fu_278_p2, icmp_ln1467_reg_576_pp0_iter2_reg, icmp_ln878_reg_592, icmp_ln870_1_reg_596)
    begin
                ap_condition_224 <= (((((icmp_ln870_1_reg_596 = ap_const_lv1_1) and (icmp_ln878_reg_592 = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_0)) or ((empty_reg_122 = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_0))) or ((icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_0))) or ((cmp57_fu_278_p2 = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_1)));
    end process;


    ap_condition_249_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
                ap_condition_249 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce));
    end process;


    ap_condition_258_assign_proc : process(icmp_ln1443_reg_541_pp0_iter1_reg, icmp_ln1443_1_reg_551_pp0_iter1_reg, and_ln1443_reg_580, and_ln1448_fu_361_p2)
    begin
                ap_condition_258 <= (((ap_const_lv1_0 = and_ln1448_fu_361_p2) and (ap_const_lv1_0 = and_ln1443_reg_580) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_lv1_0 = and_ln1448_fu_361_p2) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1443_reg_541_pp0_iter1_reg = ap_const_lv1_1)));
    end process;


    ap_condition_265_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_ce)
    begin
                ap_condition_265 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_270_assign_proc : process(icmp_ln1443_reg_541, icmp_ln1443_1_reg_551, and_ln1443_fu_312_p2)
    begin
                ap_condition_270 <= (((ap_const_lv1_1 = and_ln1443_fu_312_p2) and (icmp_ln1443_reg_541 = ap_const_lv1_0)) or ((icmp_ln1443_1_reg_551 = ap_const_lv1_1) and (icmp_ln1443_reg_541 = ap_const_lv1_1)));
    end process;


    ap_condition_277_assign_proc : process(icmp_ln1443_reg_541_pp0_iter1_reg, icmp_ln1443_1_reg_551_pp0_iter1_reg, and_ln1443_reg_580, and_ln1448_fu_361_p2)
    begin
                ap_condition_277 <= (((ap_const_lv1_1 = and_ln1448_fu_361_p2) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1443_reg_541_pp0_iter1_reg = ap_const_lv1_1)) or ((ap_const_lv1_0 = and_ln1443_reg_580) and (ap_const_lv1_1 = and_ln1448_fu_361_p2) and (icmp_ln1443_reg_541_pp0_iter1_reg = ap_const_lv1_0)));
    end process;


    ap_condition_280_assign_proc : process(icmp_ln1443_reg_541_pp0_iter1_reg, icmp_ln1443_1_reg_551_pp0_iter1_reg, and_ln1443_reg_580, and_ln1448_fu_361_p2)
    begin
                ap_condition_280 <= ((ap_const_lv1_0 = and_ln1448_fu_361_p2) and (ap_const_lv1_0 = and_ln1443_reg_580) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln1443_reg_541_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_condition_297_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, ap_ce)
    begin
                ap_condition_297 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce));
    end process;


    ap_condition_305_assign_proc : process(empty_reg_122, icmp_ln1443_1_reg_551_pp0_iter2_reg, cmp57_fu_278_p2, icmp_ln1467_reg_576_pp0_iter2_reg, icmp_ln878_reg_592, icmp_ln870_1_reg_596)
    begin
                ap_condition_305 <= (((((icmp_ln870_1_reg_596 = ap_const_lv1_1) and (icmp_ln878_reg_592 = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_1)) or ((empty_reg_122 = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_1))) or ((icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_1) and (cmp57_fu_278_p2 = ap_const_lv1_1))) or ((cmp57_fu_278_p2 = ap_const_lv1_1) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_1)));
    end process;


    ap_condition_314_assign_proc : process(empty_reg_122, icmp_ln1443_1_reg_551_pp0_iter2_reg, cmp57_fu_278_p2, icmp_ln1467_reg_576_pp0_iter2_reg, icmp_ln878_reg_592, icmp_ln870_1_reg_596)
    begin
                ap_condition_314 <= (((empty_reg_122 = ap_const_lv1_0) and (icmp_ln878_reg_592 = ap_const_lv1_1) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_1) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)) or ((empty_reg_122 = ap_const_lv1_0) and (icmp_ln870_1_reg_596 = ap_const_lv1_0) and (icmp_ln1467_reg_576_pp0_iter2_reg = ap_const_lv1_0) and (cmp57_fu_278_p2 = ap_const_lv1_1) and (icmp_ln1443_1_reg_551_pp0_iter2_reg = ap_const_lv1_0)));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_143_p4_assign_proc : process(icmp_ln1443_1_reg_551_pp0_iter1_reg, icmp_ln1467_reg_576_pp0_iter1_reg, icmp_ln878_fu_405_p2, icmp_ln870_1_fu_411_p2, sub_ln692_fu_417_p2, ap_phi_reg_pp0_iter2_storemerge_reg_140, add_ln691_2_fu_430_p2)
    begin
        if (((icmp_ln1467_reg_576_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1443_1_reg_551_pp0_iter1_reg = ap_const_lv1_0))) then
            if ((icmp_ln878_fu_405_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_storemerge_phi_fu_143_p4 <= add_ln691_2_fu_430_p2;
            elsif (((icmp_ln870_1_fu_411_p2 = ap_const_lv1_0) and (icmp_ln878_fu_405_p2 = ap_const_lv1_0))) then 
                ap_phi_mux_storemerge_phi_fu_143_p4 <= sub_ln692_fu_417_p2;
            else 
                ap_phi_mux_storemerge_phi_fu_143_p4 <= ap_phi_reg_pp0_iter2_storemerge_reg_140;
            end if;
        else 
            ap_phi_mux_storemerge_phi_fu_143_p4 <= ap_phi_reg_pp0_iter2_storemerge_reg_140;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_agg_result_0_reg_149 <= "X";
    ap_phi_reg_pp0_iter0_empty_reg_122 <= "X";
    ap_phi_reg_pp0_iter0_pix_val_V_1_reg_168 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_val_V_2_reg_185 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter2_storemerge_reg_140 <= "XXXXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to3)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= select_ln1494_2_fu_505_p3;
    ap_return_1 <= ap_phi_reg_pp0_iter4_pix_val_V_1_reg_168;
    ap_return_2 <= ap_phi_reg_pp0_iter4_pix_val_V_2_reg_185;
    blkYuv_1_address0 <= zext_ln1503_fu_462_p1(2 - 1 downto 0);

    blkYuv_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            blkYuv_1_ce0 <= ap_const_logic_1;
        else 
            blkYuv_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    cmp57_fu_278_p2 <= "1" when (color = ap_const_lv8_0) else "0";
    cmp59_fu_284_p2 <= "1" when (color = ap_const_lv8_1) else "0";
    conv_i10_fu_491_p3 <= 
        ap_const_lv8_FF when (cmp57_fu_278_p2(0) = '1') else 
        ap_const_lv8_80;
    conv_i_fu_498_p3 <= 
        ap_const_lv8_0 when (cmp57_fu_278_p2(0) = '1') else 
        ap_const_lv8_80;

    grp_reg_ap_uint_10_s_fu_301_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp33)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp33) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_reg_ap_uint_10_s_fu_301_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_ap_uint_10_s_fu_301_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_reg_ap_uint_10_s_fu_301_d <= std_logic_vector(unsigned(trunc_ln_fu_218_p4) + unsigned(ap_const_lv10_3FF));
    icmp_ln1443_1_fu_254_p2 <= "1" when (x = ap_const_lv16_0) else "0";
    icmp_ln1443_2_fu_266_p2 <= "1" when (zext_ln1443_fu_236_p1 = add_ln1443_fu_260_p2) else "0";
    icmp_ln1443_fu_240_p2 <= "1" when (y = ap_const_lv16_0) else "0";
    icmp_ln1467_fu_290_p2 <= "1" when (zext_ln1443_1_fu_250_p1 = sub29_fu_272_p2) else "0";
    icmp_ln870_1_fu_411_p2 <= "1" when (xCount_V_2 = grp_reg_ap_uint_10_s_fu_301_ap_return) else "0";
    icmp_ln870_fu_356_p2 <= "1" when (zext_ln870_fu_352_p1 = ret_fu_330_p2) else "0";
    icmp_ln878_fu_405_p2 <= "1" when (unsigned(xCount_V_2) < unsigned(grp_reg_ap_uint_10_s_fu_301_ap_return)) else "0";
    or_ln1494_fu_474_p2 <= (trunc_ln1443_reg_545_pp0_iter1_reg or cmp59_fu_284_p2);
    or_ln1503_fu_450_p2 <= (trunc_ln1443_reg_545_pp0_iter1_reg or cmp59_fu_284_p2);
    ret_fu_330_p2 <= std_logic_vector(unsigned(zext_ln1347_fu_326_p1) + unsigned(ap_const_lv11_7FF));
    select_ln1494_1_fu_467_p3 <= 
        ap_const_lv2_1 when (cmp59_fu_284_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln1494_2_fu_505_p3 <= 
        ap_const_lv8_FF when (ap_phi_reg_pp0_iter4_agg_result_0_reg_149(0) = '1') else 
        ap_const_lv8_0;
    select_ln1494_fu_478_p3 <= 
        select_ln1494_1_fu_467_p3 when (or_ln1494_fu_474_p2(0) = '1') else 
        ap_const_lv2_1;
    select_ln1503_1_fu_443_p3 <= 
        ap_const_lv2_1 when (cmp59_fu_284_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln1503_fu_454_p3 <= 
        select_ln1503_1_fu_443_p3 when (or_ln1503_fu_450_p2(0) = '1') else 
        ap_const_lv2_1;
    sub29_fu_272_p2 <= std_logic_vector(unsigned(zext_ln1435_fu_204_p1) + unsigned(ap_const_lv17_1FFFF));
    sub_ln692_fu_417_p2 <= std_logic_vector(unsigned(xCount_V_2) - unsigned(grp_reg_ap_uint_10_s_fu_301_ap_return));
    tmp_fu_316_p4 <= add_ln1437_fu_307_p2(13 downto 4);
    trunc_ln1435_fu_208_p1 <= width(14 - 1 downto 0);
    trunc_ln1437_fu_232_p1 <= height(14 - 1 downto 0);
    trunc_ln1443_fu_246_p1 <= x(1 - 1 downto 0);
    trunc_ln_fu_218_p4 <= add_ln1435_fu_212_p2(13 downto 4);
    whiYuv_1_address0 <= zext_ln1494_fu_486_p1(2 - 1 downto 0);

    whiYuv_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            whiYuv_1_ce0 <= ap_const_logic_1;
        else 
            whiYuv_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln1347_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_316_p4),11));
    zext_ln1435_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),17));
    zext_ln1437_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),17));
    zext_ln1443_1_fu_250_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x),17));
    zext_ln1443_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y),17));
    zext_ln1494_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1494_fu_478_p3),64));
    zext_ln1503_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1503_fu_454_p3),64));
    zext_ln870_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(yCount_V_2),11));
end behav;
