-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dma_demo_v_tpg_0_2_tpgForeground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    srcImg_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    srcImg_empty_n : IN STD_LOGIC;
    srcImg_read : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    patternId : IN STD_LOGIC_VECTOR (7 downto 0);
    maskId : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat : IN STD_LOGIC_VECTOR (7 downto 0);
    crossHairX : IN STD_LOGIC_VECTOR (15 downto 0);
    crossHairY : IN STD_LOGIC_VECTOR (15 downto 0);
    boxSize : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorR : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorG : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorB : IN STD_LOGIC_VECTOR (15 downto 0);
    motionSpeed : IN STD_LOGIC_VECTOR (7 downto 0);
    outImg_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    outImg_full_n : IN STD_LOGIC;
    outImg_write : OUT STD_LOGIC );
end;


architecture behav of dma_demo_v_tpg_0_2_tpgForeground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_F0 : STD_LOGIC_VECTOR (7 downto 0) := "11110000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal boxHCoord : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal boxVCoord : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal hDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal vDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal whiYuv_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal whiYuv_2_ce0 : STD_LOGIC;
    signal whiYuv_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal srcImg_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln746_reg_994 : STD_LOGIC_VECTOR (0 downto 0);
    signal outImg_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln746_reg_994_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_reg_230 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_319_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_335 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln746_fu_513_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal patternId_read_read_fu_132_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1840_fu_524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal vDir_load_load_fu_559_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1855_fu_566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1859_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hMax_fu_351_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal vMax_fu_357_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal cmp11_i106_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_fu_369_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal cmp13_i_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and4_i_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and10_i_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and24_i_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_4_fu_421_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_6_fu_441_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1867_1_fu_453_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1867_fu_457_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1919_1_fu_469_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_1_fu_487_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_1_reg_970 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln744_fu_493_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1913_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1913_reg_979 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_1_fu_503_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_1_reg_984 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln746_fu_509_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln746_reg_989 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1840_reg_998 : STD_LOGIC_VECTOR (0 downto 0);
    signal hDir_load_load_fu_530_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1845_fu_537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1849_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal vDir_load_reg_1014 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1855_reg_1018 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1859_reg_1022 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1913_fu_625_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1913_reg_1026 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1913_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1913_reg_1033 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1913_reg_1033_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_1_fu_652_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_1_reg_1042 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_2_fu_656_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_2_reg_1048 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_3_fu_666_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_3_reg_1054 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln1895_fu_740_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1895_reg_1060 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_5_fu_753_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1913_fu_760_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1913_reg_1069 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1913_1_fu_766_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1913_1_reg_1074 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1913_2_fu_773_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1913_2_reg_1079 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal y_reg_218 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_phi_mux_x_phi_fu_234_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_empty_61_phi_fu_245_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_61_reg_242 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_pix_val_V_2_phi_fu_262_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_2_reg_259 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_2_reg_259 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_val_V_1_phi_fu_277_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_1_reg_274 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_1_reg_274 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_val_V_phi_fu_293_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_reg_289 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_reg_289 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_reg_289 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1919_fu_647_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln1871_fu_582_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1869_fu_604_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxTop_fu_112 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxLeft_fu_116 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_309_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_314_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_fu_383_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_393_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_407_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_425_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_i_fu_445_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln1840_fu_518_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1913_1_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1919_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1919_fu_640_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ult_fu_692_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxBottom_fu_687_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1890_fu_710_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxRight_fu_682_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal notrhs_fu_704_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev14_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1890_1_fu_722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1890_fu_716_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1895_2_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1895_1_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1899_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1899_fu_750_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1937_fu_787_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1933_fu_780_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1935_fu_808_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_0_2_0_0_0_load_fu_794_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_62_fu_815_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_0_0_0_0_0_load_fu_801_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_344 : BOOLEAN;
    signal ap_condition_288 : BOOLEAN;
    signal ap_condition_276 : BOOLEAN;
    signal ap_condition_317 : BOOLEAN;
    signal ap_condition_392 : BOOLEAN;
    signal ap_condition_395 : BOOLEAN;
    signal ap_condition_125 : BOOLEAN;
    signal ap_condition_757 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component dma_demo_v_tpg_0_2_tpgForeground_whiYuv_2 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    whiYuv_2_U : component dma_demo_v_tpg_0_2_tpgForeground_whiYuv_2
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => whiYuv_2_address0,
        ce0 => whiYuv_2_ce0,
        q0 => whiYuv_2_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln744_fu_493_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln744_fu_493_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((icmp_ln744_fu_493_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_317)) then
                if ((ap_const_boolean_1 = ap_condition_276)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 <= pixOut_5_fu_753_p3;
                elsif ((ap_const_boolean_1 = ap_condition_288)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 <= whiYuv_2_q0;
                elsif ((ap_const_boolean_1 = ap_condition_344)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 <= srcImg_dout(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 <= ap_phi_reg_pp0_iter1_pix_val_V_1_reg_274;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_317)) then
                if ((ap_const_boolean_1 = ap_condition_276)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 <= pixOut_6_fu_441_p1;
                elsif ((ap_const_boolean_1 = ap_condition_288)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 <= pixOut_fu_369_p3;
                elsif ((ap_const_boolean_1 = ap_condition_344)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 <= srcImg_dout(23 downto 16);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 <= ap_phi_reg_pp0_iter1_pix_val_V_2_reg_259;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_val_V_reg_289_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_317)) then
                if ((ap_const_boolean_1 = ap_condition_276)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_reg_289 <= pixOut_4_fu_421_p1;
                elsif ((ap_const_boolean_1 = ap_condition_288)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_reg_289 <= ap_const_lv8_F0;
                elsif ((ap_const_boolean_1 = ap_condition_344)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_reg_289 <= pixOut_1_fu_652_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_reg_289 <= ap_phi_reg_pp0_iter1_pix_val_V_reg_289;
                end if;
            end if; 
        end if;
    end process;

    boxLeft_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                boxLeft_fu_116 <= boxHCoord;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1859_fu_577_p2 = ap_const_lv1_1) and (vDir_load_load_fu_559_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1855_fu_566_p2 = ap_const_lv1_1) and (vDir_load_load_fu_559_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln1855_fu_566_p2 = ap_const_lv1_0) and (vDir_load_load_fu_559_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)) or ((icmp_ln1859_fu_577_p2 = ap_const_lv1_0) and (vDir_load_load_fu_559_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)))))) then 
                boxLeft_fu_116 <= grp_fu_319_p3;
            end if; 
        end if;
    end process;

    boxTop_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                boxTop_fu_112 <= boxVCoord;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln1859_fu_577_p2 = ap_const_lv1_1) and (vDir_load_load_fu_559_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)) or ((icmp_ln1855_fu_566_p2 = ap_const_lv1_0) and (vDir_load_load_fu_559_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0))))) then 
                boxTop_fu_112 <= add_ln1869_fu_604_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln1859_fu_577_p2 = ap_const_lv1_0) and (vDir_load_load_fu_559_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)) or ((icmp_ln1855_fu_566_p2 = ap_const_lv1_1) and (vDir_load_load_fu_559_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0))))) then 
                boxTop_fu_112 <= sub_ln1871_fu_582_p2;
            end if; 
        end if;
    end process;

    boxVCoord_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_125)) then
                if ((ap_const_boolean_1 = ap_condition_395)) then 
                    boxVCoord <= add_ln1869_fu_604_p2;
                elsif ((ap_const_boolean_1 = ap_condition_392)) then 
                    boxVCoord <= sub_ln1871_fu_582_p2;
                end if;
            end if; 
        end if;
    end process;

    hDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_757)) then
                if (((icmp_ln1849_fu_548_p2 = ap_const_lv1_1) and (hDir_load_load_fu_530_p1 = ap_const_lv1_1))) then 
                    hDir <= ap_const_lv1_0;
                elsif (((icmp_ln1845_fu_537_p2 = ap_const_lv1_1) and (hDir_load_load_fu_530_p1 = ap_const_lv1_0))) then 
                    hDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    vDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_757)) then
                if (((icmp_ln1859_fu_577_p2 = ap_const_lv1_1) and (vDir_load_load_fu_559_p1 = ap_const_lv1_1))) then 
                    vDir <= ap_const_lv1_0;
                elsif (((icmp_ln1855_fu_566_p2 = ap_const_lv1_1) and (vDir_load_load_fu_559_p1 = ap_const_lv1_0))) then 
                    vDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    x_reg_230_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                x_reg_230 <= x_1_reg_984;
            elsif (((icmp_ln744_fu_493_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                x_reg_230 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    y_reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                y_reg_218 <= y_1_reg_970;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_reg_218 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1))) then
                and_ln1895_reg_1060 <= and_ln1895_fu_740_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_read_read_fu_132_p2 = ap_const_lv8_2) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0))) then
                and_ln1913_reg_1026 <= and_ln1913_fu_625_p2;
                or_ln1913_reg_1033 <= or_ln1913_fu_630_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter1_pix_val_V_1_reg_274 <= ap_phi_reg_pp0_iter0_pix_val_V_1_reg_274;
                ap_phi_reg_pp0_iter1_pix_val_V_2_reg_259 <= ap_phi_reg_pp0_iter0_pix_val_V_2_reg_259;
                ap_phi_reg_pp0_iter1_pix_val_V_reg_289 <= ap_phi_reg_pp0_iter0_pix_val_V_reg_289;
                x_1_reg_984 <= x_1_fu_503_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln1855_reg_1018 = ap_const_lv1_0) and (vDir_load_reg_1014 = ap_const_lv1_0) and (icmp_ln1840_reg_998 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1)) or ((icmp_ln1859_reg_1022 = ap_const_lv1_0) and (vDir_load_reg_1014 = ap_const_lv1_1) and (icmp_ln1840_reg_998 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1)))) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1859_reg_1022 = ap_const_lv1_1) and (vDir_load_reg_1014 = ap_const_lv1_1) and (icmp_ln1840_reg_998 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1855_reg_1018 = ap_const_lv1_1) and (vDir_load_reg_1014 = ap_const_lv1_0) and (icmp_ln1840_reg_998 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1)))) then
                boxHCoord <= reg_335;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0))) then
                icmp_ln1840_reg_998 <= icmp_ln1840_fu_524_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (vDir_load_load_fu_559_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0))) then
                icmp_ln1855_reg_1018 <= icmp_ln1855_fu_566_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (vDir_load_load_fu_559_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0))) then
                icmp_ln1859_reg_1022 <= icmp_ln1859_fu_577_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln744_fu_493_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln1913_reg_979 <= icmp_ln1913_fu_498_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln746_reg_994 <= icmp_ln746_fu_513_p2;
                icmp_ln746_reg_994_pp0_iter1_reg <= icmp_ln746_reg_994;
                or_ln1913_reg_1033_pp0_iter1_reg <= or_ln1913_reg_1033;
                trunc_ln746_reg_989 <= trunc_ln746_fu_509_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                pixOut_1_reg_1042 <= pixOut_1_fu_652_p1;
                pixOut_2_reg_1048 <= srcImg_dout(15 downto 8);
                pixOut_3_reg_1054 <= srcImg_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1859_fu_577_p2 = ap_const_lv1_1) and (vDir_load_load_fu_559_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1855_fu_566_p2 = ap_const_lv1_1) and (vDir_load_load_fu_559_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln1855_fu_566_p2 = ap_const_lv1_0) and (vDir_load_load_fu_559_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)) or ((icmp_ln1859_fu_577_p2 = ap_const_lv1_0) and (vDir_load_load_fu_559_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)))))) then
                reg_335 <= grp_fu_319_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_read_read_fu_132_p2 = ap_const_lv8_2))) then
                select_ln1913_1_reg_1074 <= select_ln1913_1_fu_766_p3;
                select_ln1913_2_reg_1079 <= select_ln1913_2_fu_773_p3;
                select_ln1913_reg_1069 <= select_ln1913_fu_760_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0))) then
                vDir_load_reg_1014 <= vDir;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                y_1_reg_970 <= y_1_fu_487_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0, icmp_ln746_fu_513_p2, ap_CS_fsm_state2, icmp_ln744_fu_493_p2, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln744_fu_493_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln746_fu_513_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln746_fu_513_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln1869_fu_604_p2 <= std_logic_vector(unsigned(boxTop_fu_112) + unsigned(zext_ln1867_fu_457_p1));
    and10_i_fu_401_p2 <= (tmp_fu_393_p3 and cmp11_i106_fu_363_p2);
    and24_i_fu_415_p2 <= (tmp_1_fu_407_p3 and cmp11_i106_fu_363_p2);
    and4_i_fu_387_p2 <= (empty_fu_383_p1 and cmp11_i106_fu_363_p2);
    and_ln1895_1_fu_728_p2 <= (rev14_fu_698_p2 and notrhs_fu_704_p2);
    and_ln1895_2_fu_734_p2 <= (xor_ln1890_fu_716_p2 and icmp_ln1890_1_fu_722_p2);
    and_ln1895_fu_740_p2 <= (and_ln1895_2_fu_734_p2 and and_ln1895_1_fu_728_p2);
    and_ln1899_fu_746_p2 <= (trunc_ln746_reg_989 and icmp_fu_435_p2);
    and_ln1913_fu_625_p2 <= (icmp_ln1913_reg_979 and icmp_ln1913_1_fu_620_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state6 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(srcImg_empty_n, outImg_full_n, ap_enable_reg_pp0_iter1, icmp_ln746_reg_994, ap_enable_reg_pp0_iter2, icmp_ln746_reg_994_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln746_reg_994_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (outImg_full_n = ap_const_logic_0)) or ((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (srcImg_empty_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(srcImg_empty_n, outImg_full_n, ap_enable_reg_pp0_iter1, icmp_ln746_reg_994, ap_enable_reg_pp0_iter2, icmp_ln746_reg_994_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((icmp_ln746_reg_994_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (outImg_full_n = ap_const_logic_0)) or ((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (srcImg_empty_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(srcImg_empty_n, outImg_full_n, ap_enable_reg_pp0_iter1, icmp_ln746_reg_994, ap_enable_reg_pp0_iter2, icmp_ln746_reg_994_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((icmp_ln746_reg_994_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (outImg_full_n = ap_const_logic_0)) or ((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (srcImg_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(srcImg_empty_n, icmp_ln746_reg_994)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((icmp_ln746_reg_994 = ap_const_lv1_0) and (srcImg_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage0_iter2_assign_proc : process(outImg_full_n, icmp_ln746_reg_994_pp0_iter1_reg)
    begin
                ap_block_state5_pp0_stage0_iter2 <= ((icmp_ln746_reg_994_pp0_iter1_reg = ap_const_lv1_0) and (outImg_full_n = ap_const_logic_0));
    end process;


    ap_condition_125_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_125 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_condition_276_assign_proc : process(icmp_ln746_reg_994, patternId_read_read_fu_132_p2, and_ln1895_fu_740_p2)
    begin
                ap_condition_276 <= ((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln1895_fu_740_p2) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1));
    end process;


    ap_condition_288_assign_proc : process(icmp_ln746_reg_994, patternId_read_read_fu_132_p2, or_ln1913_reg_1033)
    begin
                ap_condition_288 <= ((icmp_ln746_reg_994 = ap_const_lv1_0) and (or_ln1913_reg_1033 = ap_const_lv1_0) and (patternId_read_read_fu_132_p2 = ap_const_lv8_2));
    end process;


    ap_condition_317_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_317 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_344_assign_proc : process(icmp_ln746_reg_994, patternId_read_read_fu_132_p2)
    begin
                ap_condition_344 <= (not((patternId_read_read_fu_132_p2 = ap_const_lv8_2)) and not((patternId_read_read_fu_132_p2 = ap_const_lv8_1)) and (icmp_ln746_reg_994 = ap_const_lv1_0));
    end process;


    ap_condition_392_assign_proc : process(icmp_ln746_fu_513_p2, patternId_read_read_fu_132_p2, icmp_ln1840_fu_524_p2, vDir_load_load_fu_559_p1, icmp_ln1855_fu_566_p2, icmp_ln1859_fu_577_p2)
    begin
                ap_condition_392 <= (((icmp_ln1859_fu_577_p2 = ap_const_lv1_0) and (vDir_load_load_fu_559_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)) or ((icmp_ln1855_fu_566_p2 = ap_const_lv1_1) and (vDir_load_load_fu_559_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)));
    end process;


    ap_condition_395_assign_proc : process(icmp_ln746_fu_513_p2, patternId_read_read_fu_132_p2, icmp_ln1840_fu_524_p2, vDir_load_load_fu_559_p1, icmp_ln1855_fu_566_p2, icmp_ln1859_fu_577_p2)
    begin
                ap_condition_395 <= (((icmp_ln1859_fu_577_p2 = ap_const_lv1_1) and (vDir_load_load_fu_559_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)) or ((icmp_ln1855_fu_566_p2 = ap_const_lv1_0) and (vDir_load_load_fu_559_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)));
    end process;


    ap_condition_757_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, icmp_ln746_fu_513_p2, patternId_read_read_fu_132_p2, icmp_ln1840_fu_524_p2)
    begin
                ap_condition_757 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln746_fu_513_p2)
    begin
        if ((icmp_ln746_fu_513_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln744_fu_493_p2)
    begin
        if (((icmp_ln744_fu_493_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_empty_61_phi_fu_245_p8_assign_proc : process(icmp_ln746_fu_513_p2, patternId_read_read_fu_132_p2, icmp_ln1840_fu_524_p2, hDir_load_load_fu_530_p1, icmp_ln1845_fu_537_p2, icmp_ln1849_fu_548_p2, ap_phi_reg_pp0_iter0_empty_61_reg_242)
    begin
        if ((((icmp_ln1849_fu_548_p2 = ap_const_lv1_0) and (hDir_load_load_fu_530_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)) or ((icmp_ln1845_fu_537_p2 = ap_const_lv1_1) and (hDir_load_load_fu_530_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_empty_61_phi_fu_245_p8 <= ap_const_lv1_1;
        elsif ((((icmp_ln1845_fu_537_p2 = ap_const_lv1_0) and (hDir_load_load_fu_530_p1 = ap_const_lv1_0) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)) or ((icmp_ln1849_fu_548_p2 = ap_const_lv1_1) and (hDir_load_load_fu_530_p1 = ap_const_lv1_1) and (icmp_ln1840_fu_524_p2 = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1) and (icmp_ln746_fu_513_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_empty_61_phi_fu_245_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_61_phi_fu_245_p8 <= ap_phi_reg_pp0_iter0_empty_61_reg_242;
        end if; 
    end process;


    ap_phi_mux_pix_val_V_1_phi_fu_277_p10_assign_proc : process(icmp_ln746_reg_994_pp0_iter1_reg, patternId_read_read_fu_132_p2, or_ln1913_reg_1033_pp0_iter1_reg, pixOut_2_reg_1048, and_ln1895_reg_1060, select_ln1913_1_reg_1074, ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274)
    begin
        if ((icmp_ln746_reg_994_pp0_iter1_reg = ap_const_lv1_0)) then
            if (((ap_const_lv1_0 = and_ln1895_reg_1060) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1))) then 
                ap_phi_mux_pix_val_V_1_phi_fu_277_p10 <= pixOut_2_reg_1048;
            elsif (((or_ln1913_reg_1033_pp0_iter1_reg = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_2))) then 
                ap_phi_mux_pix_val_V_1_phi_fu_277_p10 <= select_ln1913_1_reg_1074;
            else 
                ap_phi_mux_pix_val_V_1_phi_fu_277_p10 <= ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274;
            end if;
        else 
            ap_phi_mux_pix_val_V_1_phi_fu_277_p10 <= ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274;
        end if; 
    end process;


    ap_phi_mux_pix_val_V_2_phi_fu_262_p10_assign_proc : process(icmp_ln746_reg_994_pp0_iter1_reg, patternId_read_read_fu_132_p2, or_ln1913_reg_1033_pp0_iter1_reg, pixOut_3_reg_1054, and_ln1895_reg_1060, select_ln1913_reg_1069, ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259)
    begin
        if ((icmp_ln746_reg_994_pp0_iter1_reg = ap_const_lv1_0)) then
            if (((ap_const_lv1_0 = and_ln1895_reg_1060) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1))) then 
                ap_phi_mux_pix_val_V_2_phi_fu_262_p10 <= pixOut_3_reg_1054;
            elsif (((or_ln1913_reg_1033_pp0_iter1_reg = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_2))) then 
                ap_phi_mux_pix_val_V_2_phi_fu_262_p10 <= select_ln1913_reg_1069;
            else 
                ap_phi_mux_pix_val_V_2_phi_fu_262_p10 <= ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259;
            end if;
        else 
            ap_phi_mux_pix_val_V_2_phi_fu_262_p10 <= ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259;
        end if; 
    end process;


    ap_phi_mux_pix_val_V_phi_fu_293_p10_assign_proc : process(icmp_ln746_reg_994_pp0_iter1_reg, patternId_read_read_fu_132_p2, or_ln1913_reg_1033_pp0_iter1_reg, pixOut_1_reg_1042, and_ln1895_reg_1060, select_ln1913_2_reg_1079, ap_phi_reg_pp0_iter2_pix_val_V_reg_289)
    begin
        if ((icmp_ln746_reg_994_pp0_iter1_reg = ap_const_lv1_0)) then
            if (((ap_const_lv1_0 = and_ln1895_reg_1060) and (patternId_read_read_fu_132_p2 = ap_const_lv8_1))) then 
                ap_phi_mux_pix_val_V_phi_fu_293_p10 <= pixOut_1_reg_1042;
            elsif (((or_ln1913_reg_1033_pp0_iter1_reg = ap_const_lv1_1) and (patternId_read_read_fu_132_p2 = ap_const_lv8_2))) then 
                ap_phi_mux_pix_val_V_phi_fu_293_p10 <= select_ln1913_2_reg_1079;
            else 
                ap_phi_mux_pix_val_V_phi_fu_293_p10 <= ap_phi_reg_pp0_iter2_pix_val_V_reg_289;
            end if;
        else 
            ap_phi_mux_pix_val_V_phi_fu_293_p10 <= ap_phi_reg_pp0_iter2_pix_val_V_reg_289;
        end if; 
    end process;


    ap_phi_mux_x_phi_fu_234_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln746_reg_994, x_reg_230, x_1_reg_984)
    begin
        if (((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_x_phi_fu_234_p4 <= x_1_reg_984;
        else 
            ap_phi_mux_x_phi_fu_234_p4 <= x_reg_230;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_empty_61_reg_242 <= "X";
    ap_phi_reg_pp0_iter0_pix_val_V_1_reg_274 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_val_V_2_reg_259 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_val_V_reg_289 <= "XXXXXXXX";
    ap_ready <= internal_ap_ready;
    boxBottom_fu_687_p2 <= std_logic_vector(unsigned(boxSize) + unsigned(boxTop_fu_112));
    boxRight_fu_682_p2 <= std_logic_vector(unsigned(boxSize) + unsigned(boxLeft_fu_116));
    cmp11_i106_fu_363_p2 <= "1" when (colorFormat = ap_const_lv8_0) else "0";
    cmp13_i_fu_377_p2 <= "1" when (colorFormat = ap_const_lv8_1) else "0";
    empty_62_fu_815_p3 <= 
        ap_phi_mux_pix_val_V_1_phi_fu_277_p10 when (tobool_fu_345_p2(0) = '1') else 
        select_ln1935_fu_808_p3;
    empty_fu_383_p1 <= maskId(1 - 1 downto 0);
    grp_fu_309_p2 <= std_logic_vector(unsigned(boxLeft_fu_116) - unsigned(zext_ln1867_fu_457_p1));
    grp_fu_314_p2 <= std_logic_vector(unsigned(boxLeft_fu_116) + unsigned(zext_ln1867_fu_457_p1));
    grp_fu_319_p3 <= 
        grp_fu_309_p2 when (ap_phi_mux_empty_61_phi_fu_245_p8(0) = '1') else 
        grp_fu_314_p2;
    hDir_load_load_fu_530_p1 <= hDir;
    hMax_fu_351_p2 <= std_logic_vector(unsigned(width) - unsigned(boxSize));
    icmp_fu_435_p2 <= "0" when (tmp_2_fu_425_p4 = ap_const_lv7_0) else "1";
    icmp_ln1840_fu_524_p2 <= "1" when (or_ln1840_fu_518_p2 = ap_const_lv16_0) else "0";
    icmp_ln1845_fu_537_p2 <= "1" when (unsigned(boxLeft_fu_116) > unsigned(hMax_fu_351_p2)) else "0";
    icmp_ln1849_fu_548_p2 <= "1" when (unsigned(boxLeft_fu_116) < unsigned(zext_ln1867_1_fu_453_p1)) else "0";
    icmp_ln1855_fu_566_p2 <= "1" when (unsigned(boxTop_fu_112) > unsigned(vMax_fu_357_p2)) else "0";
    icmp_ln1859_fu_577_p2 <= "1" when (unsigned(boxTop_fu_112) < unsigned(zext_ln1867_1_fu_453_p1)) else "0";
    icmp_ln1890_1_fu_722_p2 <= "1" when (unsigned(x_reg_230) < unsigned(boxRight_fu_682_p2)) else "0";
    icmp_ln1890_fu_710_p2 <= "1" when (unsigned(x_reg_230) < unsigned(boxLeft_fu_116)) else "0";
    icmp_ln1913_1_fu_620_p2 <= "0" when (ap_phi_mux_x_phi_fu_234_p4 = crossHairX) else "1";
    icmp_ln1913_fu_498_p2 <= "0" when (y_reg_218 = crossHairY) else "1";
    icmp_ln744_fu_493_p2 <= "1" when (y_reg_218 = height) else "0";
    icmp_ln746_fu_513_p2 <= "1" when (ap_phi_mux_x_phi_fu_234_p4 = width) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln744_fu_493_p2)
    begin
        if (((icmp_ln744_fu_493_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    notrhs_fu_704_p2 <= "1" when (unsigned(y_reg_218) < unsigned(boxBottom_fu_687_p2)) else "0";
    or_ln1840_fu_518_p2 <= (y_reg_218 or ap_phi_mux_x_phi_fu_234_p4);
    or_ln1913_fu_630_p2 <= (cmp11_i106_fu_363_p2 or and_ln1913_fu_625_p2);
    or_ln1919_fu_635_p2 <= (trunc_ln746_fu_509_p1 or cmp13_i_fu_377_p2);

    outImg_blk_n_assign_proc : process(outImg_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln746_reg_994_pp0_iter1_reg)
    begin
        if (((icmp_ln746_reg_994_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            outImg_blk_n <= outImg_full_n;
        else 
            outImg_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outImg_din <= ((outpix_0_2_0_0_0_load_fu_794_p3 & empty_62_fu_815_p3) & outpix_0_0_0_0_0_load_fu_801_p3);

    outImg_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln746_reg_994_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln746_reg_994_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            outImg_write <= ap_const_logic_1;
        else 
            outImg_write <= ap_const_logic_0;
        end if; 
    end process;

    outpix_0_0_0_0_0_load_fu_801_p3 <= 
        ap_phi_mux_pix_val_V_phi_fu_293_p10 when (tobool_fu_345_p2(0) = '1') else 
        select_ln1933_fu_780_p3;
    outpix_0_2_0_0_0_load_fu_794_p3 <= 
        ap_phi_mux_pix_val_V_2_phi_fu_262_p10 when (tobool_fu_345_p2(0) = '1') else 
        select_ln1937_fu_787_p3;
    patternId_read_read_fu_132_p2 <= patternId;
    pixOut_1_fu_652_p1 <= srcImg_dout(8 - 1 downto 0);
    pixOut_2_fu_656_p4 <= srcImg_dout(15 downto 8);
    pixOut_3_fu_666_p4 <= srcImg_dout(23 downto 16);
    pixOut_4_fu_421_p1 <= boxColorR(8 - 1 downto 0);
    pixOut_5_fu_753_p3 <= 
        pixOut_6_fu_441_p1 when (and_ln1899_fu_746_p2(0) = '1') else 
        trunc_ln1899_fu_750_p1;
    pixOut_6_fu_441_p1 <= boxColorB(8 - 1 downto 0);
    pixOut_fu_369_p3 <= 
        ap_const_lv8_F0 when (cmp11_i106_fu_363_p2(0) = '1') else 
        ap_const_lv8_80;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    rev14_fu_698_p2 <= (ult_fu_692_p2 xor ap_const_lv1_1);
    select_ln1913_1_fu_766_p3 <= 
        pixOut_2_fu_656_p4 when (and_ln1913_reg_1026(0) = '1') else 
        ap_const_lv8_F0;
    select_ln1913_2_fu_773_p3 <= 
        pixOut_1_fu_652_p1 when (and_ln1913_reg_1026(0) = '1') else 
        ap_const_lv8_F0;
    select_ln1913_fu_760_p3 <= 
        pixOut_3_fu_666_p4 when (and_ln1913_reg_1026(0) = '1') else 
        pixOut_fu_369_p3;
    select_ln1919_1_fu_469_p3 <= 
        ap_const_lv2_1 when (cmp13_i_fu_377_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln1919_fu_640_p3 <= 
        select_ln1919_1_fu_469_p3 when (or_ln1919_fu_635_p2(0) = '1') else 
        ap_const_lv2_1;
    select_ln1933_fu_780_p3 <= 
        ap_const_lv8_0 when (and4_i_fu_387_p2(0) = '1') else 
        ap_phi_mux_pix_val_V_phi_fu_293_p10;
    select_ln1935_fu_808_p3 <= 
        ap_const_lv8_0 when (and10_i_fu_401_p2(0) = '1') else 
        ap_phi_mux_pix_val_V_1_phi_fu_277_p10;
    select_ln1937_fu_787_p3 <= 
        ap_const_lv8_0 when (and24_i_fu_415_p2(0) = '1') else 
        ap_phi_mux_pix_val_V_2_phi_fu_262_p10;
    shl_i_fu_445_p3 <= (motionSpeed & ap_const_lv1_0);

    srcImg_blk_n_assign_proc : process(srcImg_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln746_reg_994)
    begin
        if (((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            srcImg_blk_n <= srcImg_empty_n;
        else 
            srcImg_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    srcImg_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln746_reg_994, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln746_reg_994 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            srcImg_read <= ap_const_logic_1;
        else 
            srcImg_read <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln1871_fu_582_p2 <= std_logic_vector(unsigned(boxTop_fu_112) - unsigned(zext_ln1867_fu_457_p1));
    tmp_1_fu_407_p3 <= maskId(2 downto 2);
    tmp_2_fu_425_p4 <= colorFormat(7 downto 1);
    tmp_fu_393_p3 <= maskId(1 downto 1);
    tobool_fu_345_p2 <= "1" when (maskId = ap_const_lv8_0) else "0";
    trunc_ln1899_fu_750_p1 <= boxColorG(8 - 1 downto 0);
    trunc_ln746_fu_509_p1 <= ap_phi_mux_x_phi_fu_234_p4(1 - 1 downto 0);
    ult_fu_692_p2 <= "1" when (unsigned(y_reg_218) < unsigned(boxTop_fu_112)) else "0";
    vDir_load_load_fu_559_p1 <= vDir;
    vMax_fu_357_p2 <= std_logic_vector(unsigned(height) - unsigned(boxSize));
    whiYuv_2_address0 <= zext_ln1919_fu_647_p1(2 - 1 downto 0);

    whiYuv_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            whiYuv_2_ce0 <= ap_const_logic_1;
        else 
            whiYuv_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_1_fu_503_p2 <= std_logic_vector(unsigned(ap_phi_mux_x_phi_fu_234_p4) + unsigned(ap_const_lv16_1));
    xor_ln1890_fu_716_p2 <= (icmp_ln1890_fu_710_p2 xor ap_const_lv1_1);
    y_1_fu_487_p2 <= std_logic_vector(unsigned(y_reg_218) + unsigned(ap_const_lv16_1));
    zext_ln1867_1_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_i_fu_445_p3),16));
    zext_ln1867_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(motionSpeed),16));
    zext_ln1919_fu_647_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1919_fu_640_p3),64));
end behav;
