<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" name="dma_demo_v_tpg_0_2" top="v_tpg">
    <solutions>
        <solution name="prj" status=""/>
    </solutions>
    <files>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_undistort.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_types.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_stereobm.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_mem.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_io.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_imgproc.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_imgbase.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_hough.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_histogram.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_harris.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_haar.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_fast.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_core.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_video_arithm.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls/hls_axi_io.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls_opencv.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls_video.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/v_tpg_zoneplate.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/v_tpg.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/v_tpg.cpp" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
        <file name="/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/v_tpg_config.h" sc="0" tb="false" cflags="-I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src/hls -I/home/rom41797/Documents/Project/VDMA_simple_polling_v2/project_1.gen/sources_1/bd/dma_demo/ip/dma_demo_v_tpg_0_2/src" csimflags="" blackbox="false"/>
    </files>
</AutoPilot:project>

