v_hdmirxss1_v1_0: xhdmi_example.c File Reference
xhdmi_example.c File Reference
Overview
This file demonstrates how to use Xilinx HDMI TX Subsystem, HDMI RX Subsystem and Video PHY Controller drivers.
MODIFICATION HISTORY:
Ver   Who    Date     Changes
             dd/mm/yy
1.00  YB     11/05/19 Initial release.
Functions
int I2cClk (u32 InFreq, u32 OutFreq)
This function setup SI5324 clock generator either in free or locked mode.
void Info (void)
This function outputs the video timing , Audio, Link Status, HDMI RX state of HDMI RX core.
void DetailedInfo (void)
This function prints additional details of the system for debug purpose.
void Hdmiphy1ErrorCallback (void *CallbackRef)
This function is called whenever an error condition in VPHY occurs.
void Hdmiphy1ProcessError (void)
This function is called in the application to process the pending VPHY errors.
void Exdes_CopyRxVidParamstoTx (XV_HdmiRxSs1 *HdmiRxSs1Ptr, XV_HdmiTxSs1 *HdmiTxSs1Ptr)
This function sets the colorbar output of the TX with new stream values.
u32 Exdes_SysTmrInitialize (XHdmi_Exdes *InstancePtr, u32 TmrId, u32 TmrIntrId)
This function is used to initialize the system timer that is used to count and generate given periodic interrupts.
u32 Exdes_UsToTicks (u32 TimeInUs, u32 TmrCtrClkFreq)
This function time specified in Us to ticks for a specified timer frequency.
void Exdes_StartSysTmr (XHdmi_Exdes *InstancePtr, u32 IntervalInMs)
This function is used to start a the timer to generate periodic pulses of tmrctr interrupt.
void Exdes_SysTmrCallback (void *CallbackRef, u8 TmrCtrNumber)
This function is set as the callback handler from the timer counter interrupt handler.
void Exdes_SysTimerIntrHandler (void *CallbackRef)
This function is set as the callback handler from the interrupt controller for the system timer interrupts.
void Exdes_SetDebugPrintf (Exdes_Debug_Printf PrintFunc)
This function is used to enable and additional debugging prints in the applicaiton.
void Exdes_SetAuxFifoDebugPrintf (Exdes_Debug_Printf PrintFunc)
This function is used to enable and additional debugging prints for the Aux Fifo operations in the applicaiton.
void Exdes_SetHdcpDebugPrintf (Exdes_Debug_Printf PrintFunc)
This function is used to enable and additional debugging prints for the HDCP operations in the applicaiton.
u32 XV_Tx_InitController (XV_Tx *InstancePtr, u32 HdmiTxSsDevId, u32 VPhyDevId)
This function is used to initialize the TX controller data strucuture for the HDMI 2.1 TX interrupt controller layer (see xhdmi_example_tx_sm.c/.h) Here the interrupt ids of the HDMI 2.1 TX SS and related cores are set and the HDMI 2.1 TX interrupt controller layer is initialized.
u32 XV_Rx_InitController (XV_Rx *InstancePtr, u32 HdmiRxSsDevId, u32 VPhyDevId)
This function is used to initialize the RX controller data strucuture for the HDMI 2.1 RX interrupt controller layer (see xhdmi_example_rx_sm.c/.h) Here the interrupt ids of the HDMI 2.1 RX SS and related cores are set and the HDMI 2.1 RX interrupt controller layer is initialized.
void Exdes_InitController (XHdmi_Exdes *InstancePtr)
This function is used to initialize the example desing controller data strucuture that is used to track the presence and instances of the hdmi 2.1 receiver and transmitter.
void Exdes_ChangeColorbarOutput (XVidC_VideoMode VideoMode, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc)
This function sets the colorbar output of the TX with new stream values.
void Exdes_UpdateAviInfoFrame (XVidC_VideoStream *HdmiTxSsVidStreamPtr)
This function updates the AVI Info frame for the TX stream.
void Exdes_CopyRxAVIInfoFrameToTx ()
This function copies the RX AVI Info frame to TX.
u32 Exdes_CheckDwnstrmSinkCaps ()
This function check the capabilities of the sink connected downstream to the HDMI 2.1 TX.
void Exdes_ConfigureTpgEnableInput (u32 EnableExtSrcInput)
This function configures and enables the TPG input.
void Exdes_AcrConvCfg_Passthru ()
This function configures the ACR conversion modules based on incoming ACR CTS/N Value in Pass-through Mode.
void Exdes_AudioConfig_Passthru ()
This function configures the audio for the example design when it is in pass-through mode.
void Exdes_AudioConfig_Colorbar ()
This function configures the audio for the example design when it is in colorbar mode.
void Exdes_UpdateAuxFifo ()
This function updates the global array for AUX fifo with the AUX data from the hdmi receiver.
void Exdes_SendInfoFrame_Passthru ()
This function is used to send the info frame when the example design is in pass-through mode.
void Exdes_SendInfoFrame_Colorbar ()
This function is used to send the info frame when the example design is in colorbar mode.
u32 Exdes_CheckforResChange ()
This function checks if there has been a change in resolution on the incoming rx stream.
u32 Exdes_UpdateTxParams (XHdmi_Exdes *ExdesInstance, TxInputSourceType TxInputSrc)
This function updates the parameters of the transmitter stream based on the input source for the tx stream (i.e.
TxInputSourceType Exdes_DetermineTxSrc ()
This function is used to determine the source for tx stream based on the configuration of the system and the presence/absence of rx and tx steams.
int I2cMuxSel (void *IicPtr, XOnBoard_IicDev Dev)
This function setup sets up the On Board IIC MUX to select device.
void Xil_AssertCallbackRoutine (u8 *File, s32 Line)
This is the callback for assertion error.
u32 Exdes_SetupClkSrc (u32 ps_iic0_deviceid, u32 ps_iic1_deviceid)
This function updates the FrameRate for the current video stream.
int SetupInterruptSystem (void)
This function setups the interrupt system so interrupts can occur for the HDMI cores.
int main ()
Main function to call example with HDMI TX, HDMI RX and HDMI GT drivers.
Function Documentation
void DetailedInfo (void)
This function prints additional details of the system for debug purpose.
Parameters
None.
Returns
None.
Note
None.
References XHdmi_Exdes::hdmi_rx_ctlr, XHdmi_Exdes::hdmi_tx_ctlr, XV_HdmiRxSs1::HdmiRx1Ptr, XV_HdmiRxSs1_ReportCoreInfo(), and XV_HdmiRxSs1_ReportSubcoreVersion().
void Exdes_AcrConvCfg_Passthru ()
This function configures the ACR conversion modules based on incoming ACR CTS/N Value in Pass-through Mode.
Parameters
None.
Returns
None.
Note
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by Exdes_AudioConfig_Passthru(), and Exdes_SendInfoFrame_Passthru().
void Exdes_AudioConfig_Colorbar ()
This function configures the audio for the example design when it is in colorbar mode.
Parameters
None.
Returns
None.
Note
void Exdes_AudioConfig_Passthru ()
This function configures the audio for the example design when it is in pass-through mode.
Parameters
None.
Returns
None.
Note
References Exdes_AcrConvCfg_Passthru(), XV_HdmiRxSs1_GetAudioChannels(), and XV_HdmiRxSs1_GetAudioFormat().
void Exdes_ChangeColorbarOutput (XVidC_VideoMode VideoMode, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc)
This function sets the colorbar output of the TX with new stream values.
Parameters
VideoMode is the video mode value for the new stream.
ColorFormat is the color format value for the new stream.
Bpc is the bit per color value for the new stream.
Returns
None.
Note
This API can alternatively be implemented as a generic API in the HDMI 2.1 TX interrupt controlling layer. An example of such an API maybe, XV_Tx_UpdateVidStream(XV_Tx *InstancePtr, VideoMode, Colorformat, Bpc)
References XHdmi_Exdes::ForceIndependent.
Referenced by Exdes_UpdateTxParams(), and main().
u32 Exdes_CheckDwnstrmSinkCaps ()
This function check the capabilities of the sink connected downstream to the HDMI 2.1 TX.
Returns
XST_SUCCESS if the capabilities are successfully read. XST_FAILURE otherwise.
Note
u32 Exdes_CheckforResChange ()
This function checks if there has been a change in resolution on the incoming rx stream.
Parameters
None.
Returns
None.
Note
References XV_HdmiRxSs1::IsStreamConnected, XHdmi_Exdes::TxStartTransmit, and XV_HdmiRxSs1_VRST().
Referenced by Exdes_DetermineTxSrc().
void Exdes_ConfigureTpgEnableInput (u32 EnableExtSrcInput)
This function configures and enables the TPG input.
Parameters
EnableExtSrcInput is a truth value that is used to decide if the TPG should be configured in colorbar or pass-through.
Returns
None.
Note
References XV_HdmiRxSs1_GetAviInfoframe().
void Exdes_CopyRxAVIInfoFrameToTx ()
This function copies the RX AVI Info frame to TX.
Parameters
None.
Returns
None.
Note
References XV_HdmiRxSs1_GetAviInfoframe().
void Exdes_CopyRxVidParamstoTx (XV_HdmiRxSs1 * HdmiRxSs1Ptr, XV_HdmiTxSs1 * HdmiTxSs1Ptr)
This function sets the colorbar output of the TX with new stream values.
Parameters
XV_HdmiRxSs1 is the instance of the HDMI 2.1 RX controller.
XV_HdmiTxSs1 is the instance of the HDMI 2.1 TX controller.
Returns
None.
Note
This API can alternatively be implemented as a generic API in the HDMI 2.1 TX interrupt controlling layer. An example of such an API maybe, XV_Tx_SetVidStream(XV_Tx *InstancePtr, XVidC_VideoStream *VidStreamPtr)
References XV_HdmiRxSs1_GetVideoStream().
Referenced by Exdes_UpdateTxParams().
TxInputSourceType Exdes_DetermineTxSrc ()
This function is used to determine the source for tx stream based on the configuration of the system and the presence/absence of rx and tx steams.
Parameters
None.
Returns
Returns the Tx Input source.
Note
All possible scenarios :- (Independent. 0 - PT; 1- Independent) (RX SteamOn. 0 - Rx StreamDown/Disconnect; 1 - Rx Stream Up) (TX Connected. 0 - Tx Connected and Edid read; 1- Tx Disconnected)
Independent | RX SteamOn | TX Connected | TX Source |
1 | 0 | 0 | NONE_NOCON | 1 | 0 | 1 | TPG | 1 | 1 | 0 | NONE_RXONLY | 1 | 1 | 1 | TPG | 0 | 0 | 0 | NONE_NOCON | 0 | 0 | 1 | RESCHANGE/TPG | 0 | 1 | 0 | NONE_RXONLY | 0 | 1 | 1 | INPUT_RX |
References Exdes_CheckforResChange(), XHdmi_Exdes::ForceIndependent, XHdmi_Exdes::hdmi_rx_ctlr, XHdmi_Exdes::hdmi_tx_ctlr, XHdmi_Exdes::IsRxPresent, XHdmi_Exdes::IsTxPresent, and XV_HdmiRxSs1_GetTransportMode().
Referenced by main().
void Exdes_InitController (XHdmi_Exdes * InstancePtr)
This function is used to initialize the example desing controller data strucuture that is used to track the presence and instances of the hdmi 2.1 receiver and transmitter.
Parameters
InstancePtr is the instance of the example design handle data structure.
Returns
None.
Note
References Exdes_SetAuxFifoDebugPrintf(), Exdes_SetDebugPrintf(), Exdes_SetHdcpDebugPrintf(), XHdmi_Exdes::hdmi_rx_ctlr, XHdmi_Exdes::hdmi_tx_ctlr, XHdmi_Exdes::IsRxPresent, XHdmi_Exdes::IsTxPresent, XHdmi_Exdes::SystemEvent, and XHdmi_Exdes::TxStartTransmit.
Referenced by main().
void Exdes_SendInfoFrame_Colorbar ()
This function is used to send the info frame when the example design is in colorbar mode.
Parameters
None.
Returns
None.
Note
References XHdmi_Exdes::ForceIndependent.
void Exdes_SendInfoFrame_Passthru ()
This function is used to send the info frame when the example design is in pass-through mode.
Parameters
None.
Returns
None.
Note
References Exdes_AcrConvCfg_Passthru().
void Exdes_SetAuxFifoDebugPrintf (Exdes_Debug_Printf PrintFunc)
This function is used to enable and additional debugging prints for the Aux Fifo operations in the applicaiton.
Parameters
Printfunc is the function to enable printing.
Returns
None.
Note
Referenced by Exdes_InitController().
void Exdes_SetDebugPrintf (Exdes_Debug_Printf PrintFunc)
This function is used to enable and additional debugging prints in the applicaiton.
Parameters
Printfunc is the function to enable printing.
Returns
None.
Note
Referenced by Exdes_InitController().
void Exdes_SetHdcpDebugPrintf (Exdes_Debug_Printf PrintFunc)
This function is used to enable and additional debugging prints for the HDCP operations in the applicaiton.
Parameters
Printfunc is the function to enable printing.
Returns
None.
Note
Referenced by Exdes_InitController().
u32 Exdes_SetupClkSrc (u32 ps_iic0_deviceid, u32 ps_iic1_deviceid)
This function updates the FrameRate for the current video stream.
Parameters
ps_iic0_deviceid is the device id of the ps iic device.
ps_iic1_deviceid is the device id of the ps iic device.
Returns
XST_SUCCESS if the clock source is successfuly set. XST_FAILURE otherwise.
Note
None.
References I2cMuxSel().
Referenced by main().
void Exdes_StartSysTmr (XHdmi_Exdes * InstancePtr, u32 IntervalInMs)
This function is used to start a the timer to generate periodic pulses of tmrctr interrupt.
Parameters
InstancePtr is a pointer to the example design handler.
IntervalInMs is the user specified period for the timer pulses.
Returns
None.
Note
None.
References Exdes_SysTmrCallback(), Exdes_UsToTicks(), XHdmi_Exdes::SysTmrInst, and XHdmi_Exdes::SysTmrPulseIntervalinMs.
Referenced by main().
void Exdes_SysTimerIntrHandler (void * CallbackRef)
This function is set as the callback handler from the interrupt controller for the system timer interrupts.
Parameters
InstancePtr is the callback reference.
Returns
None.
Note
None.
References XHdmi_Exdes::SysTmrInst.
Referenced by Exdes_SysTmrInitialize().
void Exdes_SysTmrCallback (void * CallbackRef, u8 TmrCtrNumber)
This function is set as the callback handler from the timer counter interrupt handler.
The counters that are used in the application for timer based control and exclusion are be handled in the this function.
The user needs to modify this callback to set the counters and exclusion flags based on the pulse counts in the pulse train generated by the system timer.
Parameters
CallbackRef is the function callback reference.
TmrCtrNumber is the timer counter number.
Returns
None.
Note
None.
References XHdmi_Exdes::hdmi_tx_ctlr.
Referenced by Exdes_StartSysTmr().
u32 Exdes_SysTmrInitialize (XHdmi_Exdes * InstancePtr, u32 TmrId, u32 TmrIntrId)
This function is used to initialize the system timer that is used to count and generate given periodic interrupts.
Parameters
InstancePtr is a pointer to the example design handler
TmrId is the device id of the system timer
TmrIntrId is the interrupt vector id of the system timer
Returns
XST_SUCCESS if successful.
Note
None.
References Exdes_SysTimerIntrHandler(), XHdmi_Exdes::hdmi_tx_ctlr, XV_Tx::Intc, and XHdmi_Exdes::SysTmrInst.
Referenced by main().
void Exdes_UpdateAuxFifo ()
This function updates the global array for AUX fifo with the AUX data from the hdmi receiver.
Parameters
None.
Returns
None.
Note
References XV_HdmiRxSs1_GetAuxiliary().
void Exdes_UpdateAviInfoFrame (XVidC_VideoStream * HdmiTxSsVidStreamPtr)
This function updates the AVI Info frame for the TX stream.
Parameters
XV_HdmiTxSsVidStreamPtr is the video stream of the HDMI 2.1 TX controller.
Returns
None.
Note
u32 Exdes_UpdateTxParams (XHdmi_Exdes * ExdesInstance, TxInputSourceType TxInputSrc)
This function updates the parameters of the transmitter stream based on the input source for the tx stream (i.e.
if the input for tx stream is the rx stream or previously set or default colorbar). rx stream.
Parameters
InstancePtr is the instance of the example design handle data structure.
TxInputSrc is the input source for the tx.
Returns
None.
Note
References Exdes_ChangeColorbarOutput(), Exdes_CopyRxVidParamstoTx(), XHdmi_Exdes::hdmi_tx_ctlr, XV_HdmiRxSs1_GetTransportMode(), XV_HdmiRxSs1_GetVideoIDCode(), and XV_HdmiRxSs1_VRST().
Referenced by main().
u32 Exdes_UsToTicks (u32 TimeInUs, u32 TmrCtrClkFreq)
This function time specified in Us to ticks for a specified timer frequency.
Parameters
TimeInUs is the time in microseconds.
TmrCtrClkFreq is the frequency of the clock to be used for counting the ticks.
Returns
Number of ticks.
Note
None.
Referenced by Exdes_StartSysTmr().
void Hdmiphy1ErrorCallback (void * CallbackRef)
This function is called whenever an error condition in VPHY occurs.
This will fill the FIFO of VPHY error events which will be processed outside the ISR.
Parameters
CallbackRef is the VPHY instance pointer
ErrIrqType is the VPHY error type
Returns
None.
Note
None.
Referenced by main().
void Hdmiphy1ProcessError (void)
This function is called in the application to process the pending VPHY errors.
Parameters
None.
Returns
None.
Note
This function can be expanded to perform necessary actions depending on the error type. For example, XHDMIPHY1_ERR_PLL_LAYOUT can be used to automatically switch in and out of bonded mode for GTXE2 devices
Referenced by main().
int I2cClk (u32 InFreq, u32 OutFreq)
This function setup SI5324 clock generator either in free or locked mode.
Parameters
Index specifies an index for selecting mode frequency.
Mode specifies either free or locked mode.
Returns
Zero if error in programming external clock.
One if programmed external clock.
Note
None.
References I2C_CLK_ADDR, and IDT_8T49N24x_I2cClk().
Referenced by main().
int I2cMuxSel (void * IicPtr, XOnBoard_IicDev Dev)
This function setup sets up the On Board IIC MUX to select device.
Parameters
None.
Returns
The number of bytes sent.
Note
None.
Referenced by Exdes_SetupClkSrc().
void Info (void)
This function outputs the video timing , Audio, Link Status, HDMI RX state of HDMI RX core.
In addition, it also prints information about HDMI TX, and HDMI GT cores.
Parameters
None.
Returns
None.
Note
None.
References XV_HdmiRxSs1::EnableHDCPLogging, XV_HdmiRxSs1_ReportAudio(), XV_HdmiRxSs1_ReportLinkQuality(), and XV_HdmiRxSs1_ReportTiming().
int main ()
Main function to call example with HDMI TX, HDMI RX and HDMI GT drivers.
Parameters
None.
Returns
XST_SUCCESS if HDMI example was successfully.
XST_FAILURE if HDMI example failed.
Note
None.
Setup IIC devices and clock sources.
Load the HDCP keys.
Initialize the Audio Generator.
Initialize the Interrupt Controller.
Initialize the HDMI Video Transmitter "state machine" functionality and the downstream HDCP device.
Initialize the HDMI Video Receiver "state machine" functionality and the downstream HDCP device.
Set the Video Phy Error callbacks.
Initialize the controller for the example design mode.
Initialize the TPG and associated GPIO to reset the TPG.
References Exdes_ChangeColorbarOutput(), Exdes_DetermineTxSrc(), Exdes_InitController(), Exdes_SetupClkSrc(), Exdes_StartSysTmr(), Exdes_SysTmrInitialize(), Exdes_UpdateTxParams(), XHdmi_Exdes::ForceIndependent, XHdmi_Exdes::hdmi_tx_ctlr, Hdmiphy1ErrorCallback(), Hdmiphy1ProcessError(), I2cClk(), XVfmc::IicPtr, XVfmc::Loc, SetupInterruptSystem(), XHdmi_Exdes::SystemEvent, XHdmi_Exdes::TxStartTransmit, XHdmi_MenuInitialize(), XHdmi_MenuProcess(), Xil_AssertCallbackRoutine(), XV_HdmiRxSs1_Start(), XV_Rx_InitController(), and XV_Tx_InitController().
int SetupInterruptSystem (void)
This function setups the interrupt system so interrupts can occur for the HDMI cores.
The function is application-specific since the actual system may or may not have an interrupt controller. The HDMI cores could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application.
Parameters
None.
Returns
XST_SUCCESS if interrupt setup was successful.
A specific error code defined in "xstatus.h" if an error occurs.
Note
This function assumes a Microblaze system and no operating system is used.
Referenced by main().
void Xil_AssertCallbackRoutine (u8 * File, s32 Line)
This is the callback for assertion error.
Parameters
File is string name of the file where the assertion failure occured.
LIne is the line wheer the assertion failure occured.
Returns
None.
Note
None.
Referenced by main().
u32 XV_Rx_InitController (XV_Rx * InstancePtr, u32 HdmiRxSsDevId, u32 VPhyDevId)
This function is used to initialize the RX controller data strucuture for the HDMI 2.1 RX interrupt controller layer (see xhdmi_example_rx_sm.c/.h) Here the interrupt ids of the HDMI 2.1 RX SS and related cores are set and the HDMI 2.1 RX interrupt controller layer is initialized.
Parameters
InstancePtr is the instance of the HDMI 2.1 RX interrupt controller layer data structure.
HdmiTxSsDevId is the device id of the HDMI 2.1 RX SS.
VPhyDevId is the device if the associated Hdmi Phy.
Returns
None.
Note
References XV_Rx::Intc, XV_Rx::VidPhy, XV_HdmiRxSS1_SetAppVersion(), XV_HdmiRxSs1_SetEdidParam(), and XV_Rx_Hdmi_Initialize().
Referenced by main().
u32 XV_Tx_InitController (XV_Tx * InstancePtr, u32 HdmiTxSsDevId, u32 VPhyDevId)
This function is used to initialize the TX controller data strucuture for the HDMI 2.1 TX interrupt controller layer (see xhdmi_example_tx_sm.c/.h) Here the interrupt ids of the HDMI 2.1 TX SS and related cores are set and the HDMI 2.1 TX interrupt controller layer is initialized.
Parameters
InstancePtr is the instance of the HDMI 2.1 TX interrupt controller layer data structure.
HdmiTxSsDevId is the device id of the HDMI 2.1 TX SS.
VPhyDevId is the device if the associated Hdmi Phy.
Returns
None.
Note
References XV_Tx::Intc, XV_Tx::VidPhy, and XV_Tx_Hdmi_Initialize().
Referenced by main().